export const LEVELS = [100, 200, 300, 400, 500, 600];

export const EXAM_STATUS = {
  UPCOMING: "upcoming",
  ONGOING: "ongoing",
  COMPLETED: "completed",
  CANCELED: "canceled",
};

export const PROGRAMS = {
  ACTUARIAL_SCIENCE: "BSc. Actuarial Science",
  AEROSPACE_ENGINEERING: "BSc. Aerospace Engineering",
  AGRIBUSINESS_MANAGEMENT: "BSc. Agribusiness Management",
  AGRICULTURAL_BIOTECHNOLOGY: "BSc. Agricultural Biotechnology",
  AGRICULTURAL_ENGINEERING: "BSc. Agricultural Engineering",
  AGRICULTURE: "BSc. Agriculture",
  AKAN_LANGUAGE: "BA. Akan Language and Culture",
  AQUACULTURE_WATER_RESOURCES:
    "BSc. Aquaculture and Water Resources Management",
  ARCHITECTURE: "BSc. Architecture",
  AUTOMOBILE_ENGINEERING: "BSc. Automobile Engineering",
  BIOCHEMISTRY: "BSc. Biochemistry",
  BIOLOGICAL_SCIENCE: "BSc. Biological Science",
  BIOMEDICAL_ENGINEERING: "BSc. Biomedical Engineering",
  BUSINESS_ADMIN_ACCOUNTING:
    "BSc. Business Administration (Accounting/Banking and Finance)",
  BUSINESS_ADMIN_HRM:
    "BSc Business Administration (Human Resource Mgt./Management)",
  BUSINESS_ADMIN_LOGISTICS_IT:
    "BSc. Business Adm. (Logistics and Supply Chain Mgt/Bus. Info.Tech.)",
  BUSINESS_ADMIN_MARKETING:
    "BSc. Business Administration (Marketing/International Business)",
  CERAMICS_TECHNOLOGY: "BSc. Ceramics Technology",
  CHEMICAL_ENGINEERING: "BSc. Chemical Engineering",
  CHEMISTRY: "BSc. Chemistry",
  CIVIL_ENGINEERING: "BSc. Civil Engineering",
  COMMUNICATION_DESIGN: "BA. Communication Design (Graphic Design)",
  COMPUTER_ENGINEERING: "BSc. Computer Engineering",
  COMPUTER_SCIENCE: "BSc. Computer Science",
  CONSTRUCTION_TECHNOLOGY: "BSc. Construction Technology and Management",
  DEVELOPMENT_PLANNING: "BSc. Development Planning",
  DIETETICS: "BSc Dietetics",
  DISABILITY_REHABILITATION: "BSc. Disability and Rehabilitation Studies",
  DENTAL_SURGERY: "Bachelor of Dental Surgery (BDS)",
  DOCTOR_OF_PHARMACY: "Pharm D (Doctor of Pharmacy)",
  DOCTOR_OF_VETERINARY_MEDICINE: "Doctor of Veterinary Medicine (DVM)",
  ECONOMICS: "BA. Economics",
  EDUCATION_JHS_SPECIALISM: "B.Ed. Junior High School Specialism",
  ELECTRICAL_ENGINEERING: "BSc. Electrical/Electronic Engineering",
  ENGLISH: "BA. English",
  ENVIRONMENTAL_SCIENCES: "BSc. Environmental Sciences",
  FASHION_DESIGN: "BSc. Fashion Design",
  FINE_ART: "BFA. Fine Art and Curatorial Practice",
  FOOD_SCIENCE: "BSc. Food Science and Technology",
  FOREST_RESOURCES_TECHNOLOGY: "BSc. Forest Resources Technology",
  FRENCH: "BA. French and Francophone Studies",
  GEOGRAPHY_RURAL_DEVELOPMENT: "BA. Geography and Rural Development",
  GEOLOGICAL_ENGINEERING: "BSc. Geological Engineering",
  GEOMATIC_ENGINEERING: "BSc. Geomatic (Geodetic) Engineering",
  HERBAL_MEDICINE: "Bachelor of Herbal Medicine (BHM)",
  HISTORY: "BA. History",
  HOSPITALITY_TOURISM: "BSc. Hospitality and Tourism Management",
  HUMAN_BIOLOGY_MEDICINE: "BSc. Human Biology (Medicine)",
  HUMAN_NUTRITION: "BSc Human Nutrition",
  HUMAN_SETTLEMENT_PLANNING: "BSc. Human Settlement Planning",
  INDUSTRIAL_ENGINEERING: "BSc. Industrial Engineering",
  INFORMATION_TECHNOLOGY: "BSc. Information Technology (IT)",
  INTEGRATED_RURAL_ART: "BA. Integrated Rural Art and Industry",
  LAND_ECONOMY: "BSc. Land Economy",
  LANDSCAPE_DESIGN: "BSc. Landscape Design and Management",
  LAW: "LLB",
  LINGUISTICS: "BA. Linguistics",
  MARINE_ENGINEERING: "BSc. Marine Engineering",
  MATERIALS_ENGINEERING: "BSc. Materials Engineering",
  MATHEMATICS: "BSc. Mathematics",
  MECHANICAL_ENGINEERING: "BSc. Mechanical Engineering",
  MEDICAL_IMAGING: "BSc. Medical Imaging",
  MEDICAL_LAB_SCIENCE: "BSc. Medical Laboratory Science",
  MEDIA_COMMUNICATION: "BA. Media and Communication Studies",
  METALLURGICAL_ENGINEERING: "BSc. Metallurgical Engineering",
  METEOROLOGY_CLIMATE: "BSc. Meteorology and Climate Science",
  MIDWIFERY: "BSc. Midwifery",
  NATURAL_RESOURCES_MANAGEMENT: "BSc. Natural Resources Management",
  NURSING: "BSc. Nursing",
  OPTOMETRY: "Doctor of Optometry",
  PACKAGING_TECHNOLOGY: "BSc. Packaging Technology",
  PETROCHEMICAL_ENGINEERING: "BSc. Petrochemical Engineering",
  PETROLEUM_ENGINEERING: "BSc. Petroleum Engineering",
  PHYSICS: "BSc. Physics",
  PHYSIOTHERAPY_SPORTS_SCIENCE: "BSc. Physiotherapy and Sports Science",
  POLITICAL_STUDIES: "BA. Political Studies",
  PUBLIC_ADMINISTRATION: "Bachelor of Public Administration",
  PUBLISHING_STUDIES: "BA. Publishing Studies",
  QUANTITY_SURVEYING: "BSc. Quantity Surveying and Construction Economics",
  REAL_ESTATE: "BSc. Real Estate",
  RELIGIOUS_STUDIES:
    "BA. Religious Studies (BA. Religion and Human Development)",
  SOCIAL_WORK: "BA. Social Work",
  SOCIOLOGY: "BA. Sociology",
  STATISTICS: "BSc. Statistics",
  TELECOMMUNICATION_ENGINEERING: "BSc. Telecommunication Engineering",
  TEXTILE_DESIGN: "BSc. Textile Design and Technology",
};
